### ISSUE TITLE
/catalog/opensearch.xml is throws an exception

### ISSUE THREAD

**Issue by jeremyf** [barmintor/dbla#8]
Running a local install on port 3000, when I go to the following URL [http://localhost:3000/?utf8=%E2%9C%93&search_field=all_fields&q=kitty](http://localhost:3000/?utf8=%E2%9C%93&search_field=all_fields&q=kitty), I get the following error. The error does not prevent rendering.

``` console
Started GET "/catalog/opensearch.xml" for ::1 at 2015-04-18 11:22:40 -0400
Processing by CatalogController#show as XML
  Parameters: {"id"=>"opensearch"}
Completed 500 Internal Server Error in 130ms (ActiveRecord: 0.0ms)

NoMethodError (undefined method `export_formats' for nil:NilClass):
  blacklight (5.13.1) lib/blacklight/catalog.rb:174:in `additional_export_formats'
  blacklight (5.13.1) lib/blacklight/catalog.rb:63:in `block in show'
  actionpack (4.2.1) lib/action_controller/metal/mime_responds.rb:210:in `respond_to'
  blacklight (5.13.1) lib/blacklight/catalog.rb:59:in `show'
```

**Comment by jeremyf** [comment]
I found the culprit:

``` console
./blacklight-5.13.1/lib/blacklight/search_helper.rb:296
```

Here is the line that returns a `solr_response.documents == []`

``` ruby
id = 'opensearch' # from input parameters
extra_controller_params = {} # from input parameters
solr_response = repository.find id, extra_controller_params
```

Here is the method's full body.

``` ruby
def fetch_one(id, extra_controller_params)
  old_solr_doc_params = Deprecation.silence(Blacklight::SearchHelper) do
    solr_doc_params(id)
  end

  if default_solr_doc_params(id) != old_solr_doc_params
    Deprecation.warn Blacklight::SearchHelper, "The #solr_doc_params method is deprecated. Instead, you should provide a custom SolrRepository implementation for the additional behavior you're offering. The current behavior will be removed in Blacklight 6.0"
    extra_controller_params = extra_controller_params.merge(old_solr_doc_params)
  end

  solr_response = repository.find id, extra_controller_params
  [solr_response, solr_response.documents.first]
end
```

**Comment by jeremyf** [comment]
It is issuing a GET request to: `http://api.dp.la/v2/items/opensearch?api_key=would_you_like_to_know`

``` ruby
module Dbla
  class Repository < Blacklight::AbstractRepository
    extend Deprecation
    self.deprecation_horizon = 'blacklight 6.0'

    def find id, params = {}
      data = get("#{url}/#{id}?api_key=#{api_key}")
      Response.new(data, params,{})
    end
  end
end
```

**Comment by jeremyf** [comment]
I assume there's an interaction with: https://github.com/projectblacklight/blacklight/blob/13adda5936014ed0711bfe5a109c6674bd762158/lib/blacklight/catalog.rb#L100-L109

**Comment by barmintor** [comment]
Hmm. This happens because /catalog/opensearch is routed through catalog#show, even though rake routes shows:

```
      opensearch_catalog GET    /catalog/opensearch(.:format)         catalog#opensearch
```

That's unexpected. Looking into it further.
